## Import Libraries

In [39]:
import pandas as pd
import numpy as np

## Load Dataset

In [40]:
df = pd.read_csv("C:\\Users\\Hey!\\OneDrive\\Desktop\\Customer churn prediction & retention Platform\\processed_data\\telecom_customer_churn_cleaned.csv")

print(df.shape)

df.head()

(7043, 31)

,CustomerID,Country,State,City,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,United States,California,Los Angeles,90003,33.964130,-118.27278,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,United States,California,Los Angeles,90005,34.059280,-118.30742,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,United States,California,Los Angeles,90006,34.048010,-118.29395,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,United States,California,Los Angeles,90010,34.062126,-118.31571,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,United States,California,Los Angeles,90015,34.039223,-118.26630,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [41]:
## Check Target Variable

df["Churn Value"].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [ ]:
## Remove Leakage Columns

drop_cols = [
    "CustomerID","Country","State","City","Zip Code",
    "Latitude","Longitude","Churn Label","Churn Reason"]

df.drop(columns=drop_cols,inplace=True)

## Investigate Churn Score

In [43]:
df[["Churn Value","Churn Score"]].corr()

             Churn Value  Churn Score
Churn Value     1.000000     0.664897
Churn Score     0.664897     1.000000

## Business Features

In [44]:
## Revenue Per Month

df["Revenue_Per_Month"] = (df["Total Charges"] /(df["Tenure Months"] + 1))

In [45]:
##  Customer Value
df["Customer_Value"] = (df["Monthly Charges"] *df["Tenure Months"])

In [47]:
## Service Count

service_cols = ["Phone Service","Multiple Lines","Online Security","Online Backup",
                "Device Protection","Tech Support","Streaming TV","Streaming Movies"]

df["Service_Count"] = (df[service_cols].eq("Yes").sum(axis=1))

## Encode Categorical Variables

In [48]:
## Check categorical columns:

cat_cols = df.select_dtypes(include="object").columns

print(cat_cols)

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method'],
      dtype='object')

In [49]:
## Use One-Hot Encoding:

df = pd.get_dummies(df,columns=cat_cols,drop_first=True)

## Check Dataset

In [50]:
print(df.shape)

df.head()

(7043, 36)

,Tenure Months,Monthly Charges,Total Charges,Churn Value,Churn Score,CLTV,Revenue_Per_Month,Customer_Value,Service_Count,Gender_Male,Senior Citizen_Yes,Partner_Yes,Dependents_Yes,Phone Service_Yes,Multiple Lines_No phone service,Multiple Lines_Yes,Internet Service_Fiber optic,Internet Service_No,Online Security_No internet service,Online Security_Yes,Online Backup_No internet service,Online Backup_Yes,Device Protection_No internet service,Device Protection_Yes,Tech Support_No internet service,Tech Support_Yes,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,2,53.85,108.15,1,86,3239,36.050000,107.7,3,True,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True
1,2,70.70,151.65,1,67,2701,50.550000,141.4,1,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,8,99.65,820.50,1,86,5372,91.166667,797.2,5,False,False,False,True,True,False,True,True,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,True,False,True,False
3,28,104.80,3046.05,1,84,5003,105.036207,2934.4,6,False,False,True,True,True,False,True,True,False,False,False,False,False,False,True,False,True,False,True,False,True,False,False,True,False,True,False
4,49,103.70,5036.30,1,89,5340,100.726000,5081.3,6,True,False,False,True,True,False,True,True,False,False,False,False,True,False,True,False,False,False,True,False,True,False,False,True,False,False,False

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 36 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Tenure Months                           7043 non-null   int64
 1   Monthly Charges                         7043 non-null   float64
 2   Total Charges                           7043 non-null   float64
 3   Churn Value                             7043 non-null   int64
 4   Churn Score                             7043 non-null   int64
 5   CLTV                                    7043 non-null   int64
 6   Revenue_Per_Month                       7043 non-null   float64
 7   Customer_Value                          7043 non-null   float64
 8   Service_Count                           7043 non-null   int64
 9   Gender_Male                             7043 non-null   bool
 10  Senior Citizen_Yes                      7043 non-null   bool
 11  Partner_Yes                             7043 non-null   bool
 12  Dependents_Yes                          7043 non-null   bool
 13  Phone Service_Yes                       7043 non-null   bool
 14  Multiple Lines_No phone service         7043 non-null   bool
 15  Multiple Lines_Yes                      7043 non-null   bool
 16  Internet Service_Fiber optic            7043 non-null   bool
 17  Internet Service_No                     7043 non-null   bool
 18  Online Security_No internet service     7043 non-null   bool
 19  Online Security_Yes                     7043 non-null   bool
 20  Online Backup_No internet service       7043 non-null   bool
 21  Online Backup_Yes                       7043 non-null   bool
 22  Device Protection_No internet service   7043 non-null   bool
 23  Device Protection_Yes                   7043 non-null   bool
 24  Tech Support_No internet service        7043 non-null   bool
 25  Tech Support_Yes                        7043 non-null   bool
 26  Streaming TV_No internet service        7043 non-null   bool
 27  Streaming TV_Yes                        7043 non-null   bool
 28  Streaming Movies_No internet service    7043 non-null   bool
 29  Streaming Movies_Yes                    7043 non-null   bool
 30  Contract_One year                       7043 non-null   bool
 31  Contract_Two year                       7043 non-null   bool
 32  Paperless Billing_Yes                   7043 non-null   bool
 33  Payment Method_Credit card (automatic)  7043 non-null   bool
 34  Payment Method_Electronic check         7043 non-null   bool
 35  Payment Method_Mailed check             7043 non-null   bool
dtypes: bool(27), float64(4), int64(5)
memory usage: 681.0 KB

## Saving Feature Engineered Dataset

In [53]:
df.to_csv("C:\\Users\\Hey!\\OneDrive\\Desktop\\Customer churn prediction & retention Platform\\processed_data\\customer_churn_feature_engineered.csv", index=False)

print("Feature Engineering Completed Successfully")

Feature Engineering Completed Successfully